In [16]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [17]:
%sql mysql+mysqlconnector://root:20056@localhost:3306/StudentsPerformance

In [18]:
%%sql
SELECT * FROM studentperformence LIMIT 5;

 * mysql+mysqlconnector://root:***@localhost:3306/StudentsPerformance
5 rows affected.

[('female', 'group B', "bachelor's degree", 'standard', 'none', 72, 72, 74),
 ('female', 'group C', 'some college', 'standard', 'completed', 69, 90, 88),
 ('female', 'group B', "master's degree", 'standard', 'none', 90, 95, 93),
 ('male', 'group A', "associate's degree", 'free/reduced', 'none', 47, 57, 44),
 ('male', 'group C', 'some college', 'standard', 'none', 76, 78, 75)]

In [20]:
from sqlalchemy import create_engine
import pandas as pd
user = 'root'
password = '20056'
host = 'localhost'
port = '3306'
database = 'StudentsPerformance' 

engine = create_engine(f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")

query = """
SELECT 
    test,
    AVG(math_score) AS avg_math,
    AVG(reading_score) AS avg_reading,
    AVG(writing_score) AS avg_writing
FROM 
    studentperformence
GROUP BY 
    test;
"""

df = pd.read_sql(query, engine)
print(df)

        test  avg_math  avg_reading  avg_writing
0       none   64.0779      66.5343      64.5047
1  completed   69.6955      73.8939      74.4190

In [25]:
%%sql 
SELECT 
    AVG(math_score) AS avg_math , 
    AVG(reading_score) AS avg_reading ,
    AVG(writing_score) AS avg_writing 
FROM 
    studentperformence 
GROUP BY 
    gender ;

 * mysql+mysqlconnector://root:***@localhost:3306/StudentsPerformance
2 rows affected.

[(Decimal('63.6332'), Decimal('72.6081'), Decimal('72.4672')),
 (Decimal('68.7282'), Decimal('65.4730'), Decimal('63.3112'))]

In [26]:
%%sql 
SELECT 
    AVG(math_score) AS avg_math , 
    AVG(reading_score) AS avg_reading ,
    AVG(writing_score) AS avg_writing 
FROM 
    studentperformence 
GROUP BY 
    lunch ;

 * mysql+mysqlconnector://root:***@localhost:3306/StudentsPerformance
2 rows affected.

[(Decimal('70.0341'), Decimal('71.6543'), Decimal('70.8233')),
 (Decimal('58.9211'), Decimal('64.6535'), Decimal('63.0225'))]

In [27]:
%%sql 
SELECT 
    AVG(math_score) AS avg_math , 
    AVG(reading_score) AS avg_reading ,
    AVG(writing_score) AS avg_writing 
FROM 
    studentperformence 
GROUP BY 
    test ;

 * mysql+mysqlconnector://root:***@localhost:3306/StudentsPerformance
2 rows affected.

[(Decimal('64.0779'), Decimal('66.5343'), Decimal('64.5047')),
 (Decimal('69.6955'), Decimal('73.8939'), Decimal('74.4190'))]

In [30]:
%%sql 
SELECT 
    parental_level_of_education , 
    ROUND(AVG((math_score + reading_score + writing_score)/3),2) AS avg_subjects 
FROM 
        studentperformence 
GROUP BY 
    parental_level_of_education 
ORDER BY 
    avg_subjects DESC ;

 * mysql+mysqlconnector://root:***@localhost:3306/StudentsPerformance
6 rows affected.

[("master's degree", Decimal('73.60')),
 ("bachelor's degree", Decimal('71.92')),
 ("associate's degree", Decimal('69.57')),
 ('some college', Decimal('68.48')),
 ('some high school', Decimal('65.11')),
 ('high school', Decimal('63.10'))]

In [34]:
%%sql 
SELECT 
    'math'  as subject , AVG(math_score)  AS avg_score 
FROM 
    studentperformence
UNION 
SELECT 
    'reading',AVG(reading_score) 
FROM 
    studentperformence 
UNION 
SELECT
   'writing',AVG(writing_score) 
FROM 
    studentperformence ;

 * mysql+mysqlconnector://root:***@localhost:3306/StudentsPerformance
3 rows affected.

[('math', Decimal('66.0890')),
 ('reading', Decimal('69.1690')),
 ('writing', Decimal('68.0540'))]

In [35]:
%%sql 
SELECT 
    AVG(math_score) AS avg_math , 
    AVG(reading_score) AS avg_reading ,
    AVG(writing_score) AS avg_writing 
FROM 
    studentperformence 
GROUP BY 
    race_ethnicity;

 * mysql+mysqlconnector://root:***@localhost:3306/StudentsPerformance
5 rows affected.

[(Decimal('63.4526'), Decimal('67.3526'), Decimal('65.6000')),
 (Decimal('64.4639'), Decimal('69.1034'), Decimal('67.8276')),
 (Decimal('61.6292'), Decimal('64.6742'), Decimal('62.6742')),
 (Decimal('67.3626'), Decimal('70.0305'), Decimal('70.1450')),
 (Decimal('73.8214'), Decimal('73.0286'), Decimal('71.4071'))]

In [37]:
%%sql 
SELECT 
    * , 
    (math_score + reading_score + writing_score ) AS total_score 
FROM 
    studentperformence
ORDER BY 
    total_score DESC ;

 * mysql+mysqlconnector://root:***@localhost:3306/StudentsPerformance
1000 rows affected.

[('female', 'group E', "bachelor's degree", 'standard', 'none', 100, 100, 100, 300),
 ('male', 'group E', "bachelor's degree", 'standard', 'completed', 100, 100, 100, 300),
 ('female', 'group E', "associate's degree", 'standard', 'none', 100, 100, 100, 300),
 ('female', 'group E', "bachelor's degree", 'standard', 'completed', 99, 100, 100, 299),
 ('female', 'group D', 'some high school', 'standard', 'completed', 97, 100, 100, 297),
 ('female', 'group D', 'some college', 'standard', 'none', 98, 100, 99, 297),
 ('female', 'group C', "bachelor's degree", 'standard', 'completed', 96, 100, 100, 296),
 ('male', 'group D', 'some college', 'standard', 'completed', 100, 97, 99, 296),
 ('male', 'group E', "associate's degree", 'free/reduced', 'completed', 100, 100, 93, 293),
 ('female', 'group E', "master's degree", 'standard', 'completed', 94, 99, 100, 293),
 ('female', 'group D', "bachelor's degree", 'free/reduced', 'completed', 93, 100, 100, 293),
 ('female', 'group E', "bachelor's degree", 'free/reduced', 'completed', 92, 100, 100, 292),
 ('female', 'group D', "master's degree", 'standard', 'none', 92, 100, 100, 292),
 ('female', 'group C', "bachelor's degree", 'standard', 'completed', 92, 100, 99, 291),
 ('female', 'group C', "associate's degree", 'standard', 'completed', 96, 96, 99, 291),
 ('female', 'group B', "bachelor's degree", 'standard', 'none', 97, 97, 96, 290),
 ('female', 'group E', 'some college', 'standard', 'none', 100, 92, 97, 289),
 ('female', 'group A', 'some high school', 'standard', 'completed', 92, 100, 97, 289),
 ('female', 'group D', "bachelor's degree", 'standard', 'none', 89, 100, 100, 289),
 ('female', 'group E', "associate's degree", 'standard', 'completed', 93, 100, 95, 288),
 ('female', 'group D', "master's degree", 'standard', 'none', 87, 100, 100, 287),
 ('female', 'group D', 'high school', 'standard', 'completed', 88, 99, 100, 287),
 ('female', 'group E', 'high school', 'standard', 'none', 99, 93, 90, 282),
 ('male', 'group C', "associate's degree", 'standard', 'completed', 87, 100, 95, 282),
 ('male', 'group A', 'some college', 'standard', 'completed', 100, 96, 86, 282),
 ('female', 'group E', "master's degree", 'standard', 'completed', 88, 99, 95, 282),
 ('male', 'group C', "associate's degree", 'standard', 'none', 97, 93, 91, 281),
 ('female', 'group D', "master's degree", 'free/reduced', 'completed', 85, 95, 100, 280),
 ('female', 'group C', "associate's degree", 'standard', 'none', 91, 95, 94, 280),
 ('male', 'group A', "bachelor's degree", 'standard', 'none', 91, 96, 92, 279),
 ('female', 'group B', "master's degree", 'standard', 'none', 90, 95, 93, 278),
 ('male', 'group C', "bachelor's degree", 'standard', 'completed', 96, 90, 92, 278),
 ('male', 'group B', 'some college', 'standard', 'completed', 91, 96, 91, 278),
 ('female', 'group C', 'some college', 'standard', 'completed', 88, 95, 94, 277),
 ('female', 'group E', "associate's degree", 'standard', 'completed', 95, 89, 92, 276),
 ('female', 'group E', "associate's degree", 'standard', 'none', 87, 94, 95, 276),
 ('female', 'group B', 'some college', 'standard', 'completed', 88, 95, 92, 275),
 ('female', 'group D', "associate's degree", 'standard', 'completed', 88, 92, 95, 275),
 ('female', 'group D', 'some college', 'standard', 'completed', 82, 97, 96, 275),
 ('male', 'group A', "associate's degree", 'standard', 'completed', 97, 92, 86, 275),
 ('male', 'group C', "bachelor's degree", 'standard', 'completed', 94, 90, 91, 275),
 ('male', 'group C', "associate's degree", 'standard', 'completed', 98, 87, 90, 275),
 ('male', 'group C', 'some college', 'standard', 'completed', 98, 86, 90, 274),
 ('female', 'group C', 'some college', 'standard', 'completed', 88, 93, 93, 274),
 ('female', 'group D', 'some high school', 'standard', 'none', 81, 97, 96, 274),
 ('female', 'group B', "associate's degree", 'standard', 'completed', 94, 87, 92, 273),
 ('male', 'group B', "associate's degree", 'standard', 'completed', 91, 89, 92, 272),
 ('female', 'group C', "bachelor's degree", 'standard', 'none', 83, 93, 95, 271),
 ('female', 'group B', "associate's degree", 'standard', 'completed', 90, 90, 91, 271),
 ('female', 'group E', "associate's degree", 'standard', 'none', 84, 95, 92, 271),
 ('female', 'group C', 'some high school', 'standard', 'completed', 85, 92, 93, 270),
 ('female', 'group C', 'some college', 'standard', 'completed', 87, 89, 94, 270),
 ('female', 'group C', "associate's degree", 'standard', 'none', 85, 89, 95, 269),
 ('female', 'group D', 'some college', 'standard', 'completed', 85, 86, 98, 269),
 ('female', 'group B', 'high school', 'standard', 'none', 87, 95, 86, 268),
 ('female', 'group C', "associate's degree", 'free/reduced', 'completed', 82, 93, 93, 268),
 ('female', 'group B', "master's degree", 'free/reduced', 'completed', 77, 97, 94, 268),
 ('female', 'group A', "associate's degree", 'standard', 'none', 82, 93, 93, 268),
 ('male', 'group E', "associate's degree", 'standard', 'completed', 97, 82, 88, 267),
 ('male', 'group E', 'some college', 'standard', 'completed', 99, 87, 81, 267),
 ('male', 'group C', 'some college', 'standard', 'completed', 93, 84, 90, 267),
 ('male', 'group B', 'some high school', 'standard', 'completed', 94, 86, 87, 267),
 ('female', 'group A', 'some high school', 'standard', 'completed', 85, 90, 92, 267),
 ('male', 'group E', 'some college', 'standard', 'none', 97, 87, 82, 266),
 ('female', 'group C', 'some college', 'standard', 'none', 82, 90, 94, 266),
 ('female', 'group C', "bachelor's degree", 'standard', 'completed', 77, 94, 95, 266),
 ('female', 'group D', "associate's degree", 'standard', 'none', 82, 95, 89, 266),
 ('male', 'group E', 'some college', 'free/reduced', 'none', 93, 90, 83, 266),
 ('female', 'group D', "associate's degree", 'standard', 'none', 85, 91, 89, 265),
 ('female', 'group C', "bachelor's degree", 'standard', 'none', 86, 92, 87, 265),
 ('male', 'group B', "bachelor's degree", 'free/reduced', 'completed', 87, 90, 88, 265),
 ('female', 'group E', 'some college', 'standard', 'none', 87, 85, 93, 265),
 ('female', 'group D', "master's degree", 'standard', 'none', 78, 91, 96, 265),
 ('female', 'group D', "associate's degree", 'free/reduced', 'completed', 77, 89, 98, 264),
 ('female', 'group E', "master's degree", 'standard', 'none', 81, 92, 91, 264),
 ('male', 'group C', 'high school', 'standard', 'none', 88, 89, 86, 263),
 ('male', 'group D', "master's degree", 'free/reduced', 'completed', 84, 89, 90, 263),
 ('female', 'group C', 'some college', 'standard', 'none', 84, 87, 91, 262),
 ('male', 'group D', "associate's degree", 'standard', 'none', 90, 87, 85, 262),
 ('male', 'group E', "associate's degree", 'free/reduced', 'none', 90, 90, 82, 262),
 ('female', 'group E', 'some college', 'standard', 'completed', 86, 85, 91, 262),
 ('female', 'group E', "associate's degree", 'standard', 'none', 85, 92, 85, 262),
 ('female', 'group C', "associate's degree", 'standard', 'none', 91, 86, 84, 261),
 ('female', 'group E', "associate's degree", 'standard', 'completed', 79, 88, 94, 261),
 ('female', 'group B', 'high school', 'standard', 'none', 81, 91, 89, 261),
 ('male', 'group E', "associate's degree", 'standard', 'completed', 94, 85, 82, 261),
 ('female', 'group D', "bachelor's degree", 'free/reduced', 'none', 78, 90, 93, 261),
 ('male', 'group C', "master's degree", 'standard', 'completed', 91, 85, 85, 261),
 ('female', 'group C', "bachelor's degree", 'standard', 'completed', 79, 92, 89, 260),
 ('male', 'group E', 'some high school', 'standard', 'none', 94, 88, 78, 260),
 ('male', 'group D', "master's degree", 'standard', 'none', 95, 81, 84, 260),
 ('female', 'group D', 'some high school', 'standard', 'completed', 80, 92, 88, 260),
 ('female', 'group C', "master's degree", 'standard', 'completed', 81, 91, 87, 259),
 ('male', 'group E', 'high school', 'standard', 'completed', 87, 91, 81, 259),
 ('female', 'group D', 'some college', 'standard', 'none', 80, 90, 89, 259),
 ('male', 'group D', 'some high school', 'standard', 'completed', 89, 88, 82, 259),
 ('female', 'group C', "bachelor's degree", 'standard', 'none', 81, 88, 90, 259),
 ('male', 'group E', "master's degree", 'standard', 'none', 90, 85, 84, 259),
 ('female', 'group C', 'some college', 'free/reduced', 'none', 77, 90, 91, 258),
 ('female', 'group C', "associate's degree", 'standard', 'completed', 83, 85, 90, 258),
 ('male', 'group A', "bachelor's degree", 'standard', 'completed', 87, 84, 87, 258),
 ('male', 'group D', "master's degree", 'standard', 'none', 85, 84, 89, 258),
 ('female', 'group B', 'some college', 'standard', 'none', 79, 86, 92, 257),
 ('female', 'group E', "associate's degree", 'free/reduced', 'completed', 83, 86, 88, 257),
 ('male', 'group E', 'some high school', 'standard', 'none', 92, 87, 78, 257),
 ('female', 'group D', "bachelor's degree", 'standard', 'none', 79, 89, 89, 257),
 ('female', 'group B', "associate's degree", 'free/reduced', 'completed', 76, 94, 87, 257),
 ('male', 'group B', 'some college', 'standard', 'completed', 87, 84, 86, 257),
 ('male', 'group D', "associate's degree", 'standard', 'completed', 87, 84, 85, 256),
 ('female', 'group C', 'some college', 'standard', 'none', 83, 83, 90, 256),
 ('female', 'group C', 'some high school', 'standard', 'none', 77, 91, 88, 256),
 ('female', 'group A', 'some college', 'standard', 'completed', 78, 87, 91, 256),
 ('male', 'group D', "master's degree", 'standard', 'none', 89, 84, 82, 255),
 ('male', 'group C', "bachelor's degree", 'standard', 'none', 86, 83, 86, 255),
 ('male', 'group D', 'high school', 'standard', 'none', 89, 87, 79, 255),
 ('male', 'group C', "associate's degree", 'standard', 'none', 92, 79, 84, 255),
 ('female', 'group D', 'some college', 'free/reduced', 'none', 79, 89, 86, 254),
 ('female', 'group B', 'some college', 'standard', 'none', 82, 85, 87, 254),
 ('female', 'group E', "master's degree", 'free/reduced', 'none', 81, 86, 87, 254),
 ('female', 'group D', 'some college', 'standard', 'completed', 79, 84, 91, 254),
 ('female', 'group D', "associate's degree", 'free/reduced', 'completed', 75, 90, 88, 253),
 ('female', 'group E', "associate's degree", 'standard', 'completed', 82, 85, 86, 253),
 ('female', 'group C', "bachelor's degree", 'standard', 'none', 77, 88, 87, 252),
 ('male', 'group D', "associate's degree", 'free/reduced', 'none', 90, 87, 75, 252),
 ('female', 'group D', 'some high school', 'standard', 'none', 80, 90, 82, 252),
 ('female', 'group D', "associate's degree", 'free/reduced', 'completed', 74, 88, 90, 252),
 ('female', 'group B', 'some high school', 'free/reduced', 'completed', 74, 90, 88, 252),
 ('female', 'group C', 'some high school', 'standard', 'completed', 77, 90, 85, 252),
 ('male', 'group D', 'some college', 'standard', 'completed', 82, 82, 88, 252),
 ('male', 'group C', 'some college', 'standard', 'none', 84, 87, 81, 252),
 ('female', 'group C', "associate's degree", 'standard', 'none', 85, 84, 82, 251),
 ('female', 'group B', "master's degree", 'standard', 'none', 77, 90, 84, 251),
 ('male', 'group C', "bachelor's degree", 'standard', 'completed', 91, 81, 79, 251),
 ('male', 'group D', 'some college', 'standard', 'completed', 85, 81, 85, 251),
 ('female', 'group D', "master's degree", 'standard', 'completed', 77, 82, 91, 250),
 ('female', 'group A', 'high school', 'free/reduced', 'completed', 77, 88, 85, 250),
 ('female', 'group E', 'some high school', 'standard', 'completed', 80, 85, 85, 250),
 ('male', 'group E', 'some high school', 'standard', 'completed', 89, 84, 77, 250),
 ('male', 'group B', 'some high school', 'standard', 'completed', 79, 85, 86, 250),
 ('male', 'group C', "bachelor's degree", 'standard', 'completed', 83, 82, 84, 249),
 ('male', 'group B', 'some college', 'standard', 'completed', 88, 85, 76, 249),
 ('male', 'group B', "associate's degree", 'standard', 'none', 90, 78, 81, 249),
 ('female', 'group B', "associate's degree", 'standard', 'none', 80, 86, 83, 249),
 ('male', 'group D', "bachelor's degree", 'standard', 'none', 88, 78, 83, 249),
 ('female', 'group B', "bachelor's degree", 'free/reduced', 'none', 77, 85, 87, 249),
 ('female', 'group D', 'high school', 'free/reduced', 'none', 73, 92, 84, 249),
 ('female', 'group C', "bachelor's degree", 'free/reduced', 'completed', 74, 86, 89, 249),
 ('female', 'group D', 'some college', 'free/reduced', 'none', 77, 86, 86, 249),
 ('male', 'group C', 'high school', 'standard', 'completed', 82, 84, 82, 248),
 ('female', 'group E', 'some college', 'free/reduced', 'completed', 75, 88, 85, 248),
 ('female', 'group C', 'some high school', 'standard', 'completed', 76, 87, 85, 248),
 ('female', 'group C', 'high school', 'standard', 'none', 75, 88, 85, 248),
 ('male', 'group D', 'some high school', 'standard', 'none', 84, 84, 80, 248),
 ('female', 'group B', 'high school', 'standard', 'completed', 77, 82, 89, 248),
 ('female', 'group C', 'some college', 'standard', 'completed', 69, 90, 88, 247),
 ('female', 'group C', 'some college', 'free/reduced', 'none', 76, 83, 88, 247),
 ('male', 'group B', 'some high school', 'standard', 'none', 88, 84, 75, 247),
 ('female', 'group C', 'some college', 'standard', 'completed', 70, 89, 88, 247),
 ('male', 'group B', 'some high school', 'standard', 'completed', 85, 84, 78, 247),
 ('male', 'group C', 'high school', 'standard', 'completed', 86, 81, 80, 247),
 ('female', 'group D', 'some college', 'standard', 'none', 74, 89, 84, 247),
 ('female', 'group C', "associate's degree", 'standard', 'completed', 75, 82, 90, 247),
 ('female', 'group C', 'high school', 'standard', 'none', 81, 84, 82, 247),
 ('male', 'group E', 'some high school', 'standard', 'completed', 87, 84, 76, 247),
 ('male', 'group D', 'some college', 'standard', 'none', 81, 82, 84, 247),
 ('female', 'group D', 'some college', 'standard', 'none', 79, 86, 81, 246),
 ('female', 'group E', "bachelor's degree", 'standard', 'none', 80, 83, 83, 246),
 ('male', 'group D', "master's degree", 'standard', 'none', 81, 81, 84, 246),
 ('male', 'group B', "associate's degree", 'standard', 'none', 87, 85, 73, 245),
 ('male', 'group B', "associate's degree", 'standard', 'completed', 81, 82, 82, 245),
 ('male', 'group E', 'some college', 'standard', 'completed', 84, 83, 78, 245),
 ('male', 'group D', 'some high school', 'standard', 'completed', 78, 81, 86, 245),
 ('male', 'group C', "associate's degree", 'standard', 'none', 84, 80, 80, 244),
 ('female', 'group B', 'some high school', 'standard', 'none', 82, 82, 80, 244),
 ('male', 'group E', "associate's degree", 'free/reduced', 'completed', 91, 73, 80, 244),
 ('male', 'group B', "associate's degree", 'standard', 'completed', 82, 84, 78, 244),
 ('male', 'group B', 'high school', 'standard', 'none', 82, 82, 80, 244),
 ('male', 'group A', "associate's degree", 'free/reduced', 'completed', 79, 82, 82, 243),
 ('female', 'group B', 'high school', 'free/reduced', 'completed', 76, 85, 82, 243),
 ('female', 'group C', 'some high school', 'free/reduced', 'completed', 71, 84, 87, 242),
 ('female', 'group B', "bachelor's degree", 'free/reduced', 'none', 75, 85, 82, 242),
 ('male', 'group B', 'some high school', 'standard', 'completed', 84, 83, 75, 242),
 ('female', 'group D', 'some high school', 'standard', 'none', 73, 84, 85, 242),
 ('female', 'group E', "bachelor's degree", 'standard', 'completed', 79, 81, 82, 242),
 ('male', 'group D', 'some college', 'standard', 'none', 88, 77, 77, 242),
 ('male', 'group E', 'high school', 'free/reduced', 'completed', 86, 81, 75, 242),
 ('male', 'group E', "associate's degree", 'standard', 'completed', 81, 81, 79, 241),
 ('male', 'group D', 'high school', 'standard', 'none', 88, 78, 75, 241),
 ('female', 'group D', 'some high school', 'standard', 'none', 73, 86, 82, 241),
 ('male', 'group C', "associate's degree", 'free/reduced', 'completed', 78, 81, 82, 241),
 ('male', 'group D', 'some high school', 'standard', 'none', 86, 80, 75, 241),
 ('male', 'group C', 'some college', 'standard', 'none', 91, 74, 76, 241),
 ('male', 'group D', "associate's degree", 'free/reduced', 'completed', 79, 82, 80, 241),
 ('male', 'group E', 'some high school', 'free/reduced', 'completed', 78, 83, 80, 241),
 ('female', 'group C', 'some college', 'standard', 'completed', 75, 81, 84, 240),
 ('male', 'group A', 'some college', 'free/reduced', 'completed', 81, 78, 81, 240),
 ('female', 'group E', 'high school', 'standard', 'none', 75, 86, 79, 240),
 ('female', 'group B', 'high school', 'free/reduced', 'none', 71, 87, 82, 240),
 ('male', 'group A', "bachelor's degree", 'standard', 'completed', 80, 78, 81, 239),
 ('female', 'group D', "bachelor's degree", 'standard', 'none', 78, 82, 79, 239),
 ('male', 'group D', 'some college', 'standard', 'none', 88, 73, 78, 239),
 ('male', 'group E', "associate's degree", 'standard', 'none', 89, 76, 74, 239),
 ('male', 'group B', "bachelor's degree", 'free/reduced', 'none', 88, 75, 76, 239),
 ('female', 'group B', "associate's degree", 'standard', 'none', 82, 80, 77, 239),
 ('female', 'group D', 'high school', 'standard', 'none', 78, 81, 80, 239),
 ('female', 'group B', "bachelor's degree", 'standard', 'none', 75, 84, 80, 239),
 ('female', 'group D', "associate's degree", 'standard', 'none', 74, 81, 83, 238),
 ('male', 'group D', "master's degree", 'standard', 'none', 82, 82, 74, 238),
 ('male', 'group D', 'some college', 'standard', 'completed', 76, 83, 79, 238),
 ('female', 'group C', "master's degree", 'standard', 'completed', 69, 84, 85, 238),
 ('male', 'group D', 'some high school', 'free/reduced', 'completed', 80, 79, 79, 238),
 ('female', 'group B', 'some high school', 'standard', 'none', 67, 89, 82, 238),
 ('female', 'group C', "associate's degree", 'standard', 'completed', 68, 86, 84, 238),
 ('male', 'group E', 'high school', 'standard', 'none', 94, 73, 71, 238),
 ('female', 'group C', "associate's degree", 'standard', 'completed', 67, 84, 86, 237),
 ('male', 'group E', 'high school', 'standard', 'completed', 81, 80, 76, 237),
 ('female', 'group D', 'some college', 'free/reduced', 'none', 71, 83, 83, 237),
 ('male', 'group E', "associate's degree", 'standard', 'none', 87, 74, 76, 237),
 ('female', 'group C', "associate's degree", 'standard', 'none', 81, 77, 79, 237),
 ('male', 'group D', 'some high school', 'standard', 'completed', 88, 74, 75, 237),
 ('male', 'group D', 'some high school', 'standard', 'none', 81, 78, 78, 237),
 ('male', 'group E', 'some college', 'standard', 'none', 83, 80, 73, 236),
 ('female', 'group B', "bachelor's degree", 'standard', 'none', 67, 86, 83, 236),
 ('male', 'group C', 'some college', 'standard', 'completed', 79, 79, 78, 236),
 ('female', 'group D', "bachelor's degree", 'free/reduced', 'none', 73, 79, 84, 236),
 ('female', 'group E', 'some high school', 'standard', 'none', 77, 79, 80, 236),
 ('male', 'group E', 'some college', 'standard', 'none', 86, 76, 74, 236),
 ('female', 'group D', 'some high school', 'free/reduced', 'completed', 69, 86, 81, 236),
 ('female', 'group A', 'high school', 'standard', 'completed', 75, 82, 79, 236),
 ('female', 'group D', 'some college', 'free/reduced', 'completed', 67, 86, 83, 236),
 ('female', 'group C', 'some college', 'standard', 'none', 73, 80, 82, 235),
 ('male', 'group C', 'high school', 'standard', 'none', 84, 77, 74, 235),
 ('male', 'group D', 'high school', 'free/reduced', 'completed', 78, 77, 80, 235),
 ('female', 'group D', "master's degree", 'standard', 'none', 74, 79, 82, 235),
 ('female', 'group E', "associate's degree", 'free/reduced', 'none', 70, 84, 81, 235),
 ('female', 'group C', 'high school', 'standard', 'none', 72, 80, 83, 235),
 ('female', 'group D', 'some high school', 'free/reduced', 'none', 67, 84, 84, 235),
 ('female', 'group A', 'some college', 'standard', 'none', 69, 84, 82, 235),
 ('female', 'group D', 'some college', 'standard', 'completed', 75, 77, 83, 235),
 ('female', 'group B', "associate's degree", 'standard', 'completed', 61, 86, 87, 234),
 ('male', 'group B', "associate's degree", 'free/reduced', 'completed', 82, 78, 74, 234),

In [38]:
%%sql 
SELECT 
    gender , 
    SUM( 
        CASE WHEN ( math_score + reading_score + writing_score ) >= 240 THEN 1 ELSE 0 END ) AS high_performance 
FROM 
    studentperformence 
GROUP BY 
    gender ;

 * mysql+mysqlconnector://root:***@localhost:3306/StudentsPerformance
2 rows affected.

[('female', Decimal('118')), ('male', Decimal('80'))]

In [40]:
%%sql
SELECT 
    gender, 
    SUM(CASE 
            WHEN (math_score + reading_score + writing_score) >= 240 
            THEN 1 
            ELSE 0 
        END) AS high_performance,

    SUM(CASE 
            WHEN (math_score + reading_score + writing_score) >= 180 
             AND (math_score + reading_score + writing_score) < 240
            THEN 1 
            ELSE 0 
        END) AS average_performance,

    SUM(CASE 
            WHEN (math_score + reading_score + writing_score) < 180 
            THEN 1 
            ELSE 0 
        END) AS low_performance

FROM studentperformence
GROUP BY gender;

 * mysql+mysqlconnector://root:***@localhost:3306/StudentsPerformance
2 rows affected.

[('female', Decimal('118'), Decimal('276'), Decimal('124')),
 ('male', Decimal('80'), Decimal('241'), Decimal('161'))]